### ISSUE TITLE
Save metadata source

### ISSUE THREAD

**Issue by Slesarew** [paritytech/metadata-portal#106]
When metadata is fetched from network, record block it was generated for. When it is generated from github, identify source as well (wasm hash maybe?)

This is needed to track silent metadata changes. One just happened recently in Acala. This severely breaks signer functionality (other clients functionality as well probably) and might result in harmful consequences, so we should actively fight it.

**Comment by Slesarew** [comment]
For reference https://github.com/AcalaNetwork/Acala/issues/2184

**Comment by prybalko** [comment]
Fixed by https://github.com/paritytech/metadata-portal/pull/127
