### ISSUE TITLE
How add other network like Efinity?

### ISSUE THREAD

**Issue by ccfiel** [paritytech/metadata-portal#273]
how can I add network in metadata parity https://metadata.parity.io/ there are only 3 network available or is there any other site with complete network?

**Comment by ccfiel** [comment]
how can I add network in metadata parity https://metadata.parity.io/ there are only 3 network or is there any other site with complete network?

**Comment by prybalko** [comment]
Parity-hosted site only hosts metadata for networks Parity actively participates in.
Anyone can fork https://github.com/paritytech/metadata-portal/ and host their own version, with their own networks (and their own trust keys); this doesn't even require any server — only a Github account and optionally a domain name.
One of the largest independently-run metadata portals is https://nova-wallet.github.io/metadata-portal, by the awesome folks from Nova Wallet team

**Comment by ccfiel** [comment]
thanks for this @prybalko :)

**Comment by ccfiel** [comment]
@prybalko I did try your suggestion to use https://nova-wallet.github.io/metadata-portal/#/efinity and scan the QR code but I got this error any idea why?
![Screenshot_20220808-173242_Parity_Signer](https://user-images.githubusercontent.com/1788360/183387869-e5bbff10-2a55-49a2-a23e-460c5ffe43ff.jpg)

**Comment by ccfiel** [comment]
@prybalko  I also try to scan the chain specs here https://nova-wallet.github.io/metadata-portal/#/efinity and https://metadata.parity.io/#/westend but I got this error Corrupted data. Bad signature. What did I do wrong?

![ksnip_20220808-180737](https://user-images.githubusercontent.com/1788360/183409749-9f12c151-22a5-417a-b3cf-5bb11363f5e5.png)

![Screenshot_20220808-180704_Parity_Signer](https://user-images.githubusercontent.com/1788360/183409811-a4b4cbc8-4f91-44c3-b88e-5d4aa5c07e39.jpg)

**Comment by prybalko** [comment]
@ccfiel what Signer version are you using? I cannot replicate the issue.

<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/7165377/183423901-804f037d-07d2-4660-9fdc-dec0b863fee5.png)
  
</details>

**Comment by ccfiel** [comment]
@prybalko it's 4.6.6 is there a new version?

**Comment by prybalko** [comment]
Currently it's 5.0.0. Available on App store and Google play

**Comment by ccfiel** [comment]
thanks, it works now :)
