### ISSUE TITLE
Use github repo for different chains

### ISSUE THREAD

**Issue by pgolovkin** [paritytech/metadata-portal#390]
### The problem
The metadata portal with different [parachains support is hosted](https://nova-wallet.github.io/metadata-portal/#/). I'd like to user the update from github repositories approach for parachains where it's possible. However I can't find a way how the github repo may be specified for each parachain. For example for Acala and for Statemine.

Could you please point me how it may be achieved or work on the solution for it?

**Comment by prybalko** [comment]
At the moment, github repository for updates is a global setting https://github.com/paritytech/metadata-portal/blob/master/config.toml#L9. I agree that it should be moved on `[[chains]]` level

**Comment by pgolovkin** [comment]
Agree that moving github setting to the `[[chains]]` level will be a good solution.
