### ISSUE TITLE
Invalid cross-device link when building updater.

### ISSUE THREAD

**Issue by Zerophase** [paritytech/metadata-portal#535]
I'm trying to build the Updater on an Arch System.  Whenever I run `make updater` I receive error message of:

> cargo run --release update
>     Finished release [optimized] target(s) in 0.40s
>      Running `target/release/metadata-cli update`
> [2023-01-29T22:05:19Z INFO ] ⚙️  Generating unsigned_kusama_metadata_9370.apng...
> [2023-01-29T22:05:22Z ERROR] Invalid cross-device link (os error 18)
> make: *** [Makefile:14: updater] Error 1

**Comment by Zerophase** [comment]
Looks like an issue with OverlayFS filesystems in ram. https://github.com/rust-lang/rustup/issues/1239

**Comment by prybalko** [comment]
@Zerophase Right, please try to remove and reinstall your toolchains. Feel free to close the issue if it works

**Comment by Zerophase** [comment]
Just got my development machine back up. Other than reinstalling rust, which libraries should I reinstall.

**Comment by Zerophase** [comment]
Yeah, it's still giving invalid cross device link.

**Comment by FlorianFranzen** [comment]
I had this issue ever since using this tool, even makes tests like `save_and_read_img_source` fail.
