### ISSUE TITLE
Show the state when the chain was added on the metadata portal but it's metadata is outdated for some reason

### ISSUE THREAD

**Issue by pgolovkin** [paritytech/metadata-portal#587]
Show the state when the chain was added on the metadata portal but it's metadata is outdated for some reason

The case:
1. Metadata portal updates the metadata for all added network into the chains.json file
2. After the update Metadata portal deplyes new QR codes
3. During the metadata deploy metadata portal realises that for some chain metadata is already outdated (while collect is working)
4. As a result network with outdated metadata disappear from the metadata portal that confuse users.

**Comment by prybalko** [comment]
Thank you for reporting. Confirmed.
