### ISSUE TITLE
Feat request: Add coretime chain

### ISSUE THREAD

**Issue by wischli** [paritytech/metadata-portal#754]
Unfortunately, the Kusama coretime chain is missing in the metadata portal such that signing transactions on it is impossible for a PVault account AFAICT. Since Kusama renewals are active now, I hope this can be done ASAP!

**Comment by FlorianFranzen** [comment]
If you add it to the `config.toml` in a PR, the maintainer will get a signing request once merged.

**Comment by wischli** [comment]
I have no association with the Kusama Coretime chain. I am just a desperate user who expects the Parity Metadata portal to provide an "official" chain spec and metadata for a system parachain! I don't understand why Kusama People is already included in the metadata portal but the chain necessary to renew parachain cores is not? The current fallback to use the 3rd party portal from Novasama.

**Comment by wischli** [comment]
Pinging @SBalaguer here

**Comment by EgorPopelyaev** [comment]
Kusama Coretime metadata are added to the portal

**Comment by SBalaguer** [comment]
Thans @EgorPopelyaev! Closing this issue for now :)
